### ISSUE TITLE
Replace RemoteProfile with File Link

### ISSUE THREAD

**Issue by ac87** [ac87/brouter-android-lib#1]
It makes no sense for an app to load a file, pass it as text, the library to save it and then use it.

**Comment by ac87** [comment]
Currently the profile has to be loaded from the same directory as the lookup.dat is stored so either the app needs to be store the profile in the same directory or have the library do it.
```
java.lang.RuntimeException: java.io.FileNotFoundException: /data/user/0/com.routing.brouter.test/files/lookups.dat (No such file or directory)
at btools.expressions.BExpressionMetaData.readMetaData(BExpressionMetaData.java:86)
at btools.router.ProfileCache.parseProfile(ProfileCache.java:107)
at btools.router.RoutingEngine.<init>(RoutingEngine.java:104)
at com.routing.brouter.BRouter.generateRoute(BRouter.kt:108)
```
